### ISSUE TITLE
Issue running on AWS Lambda

### ISSUE THREAD

**Issue by conor-deegan** [eugeneware/ffmpeg-static#122]
I am using ffmpeg-static in a containerised Lambda function. Running locally, the container executes fine. On Lambda, I get a `SIGSEGV` fault for larger ffmpeg jobs.

```
ffmpeg was killed with signal SIGSEGV
```

I am considering creating my own binary, but wanted to check if this is something that can be updated here?

**Comment by derhuerst** [comment]
This project merely packages binaries prebuilt by others. I cannot provide support for problems with ffmpeg *itself* here.

Most likely this is due to the constrained environment AWS Lambda executes code in, or due to the way you run `ffmpeg`. In case you identify the problem, please don't hesitate to document a solution/workaround here though!
