### ISSUE TITLE
bug: unable to install with nvm

### ISSUE THREAD

**Issue by Goddard** [eugeneware/ffmpeg-static#127]
### ffmpeg-static version

whatever the latest from npm

### Node.js version

16.20.0

### operating system and/or environment

Manjaro host with ubutnu docker image
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

### What happened?

npm install --save ffmpeg-static
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! /bin/bash: node: command not found

I am using nvm and it appears it can't find node.

which node
/root/.nvm/versions/node/v16.20.0/bin/node

**Comment by ralyodio** [comment]
add to your path in .bashrc

**Comment by Goddard** [comment]
it is that is how i can execute it and use 'which node' in order to provide you the full path.

**Comment by derhuerst** [comment]
This problem seems unrelated to `ffmpeg-static`, but rather to your nvm installation, so I'm going to close it. Sorry.

The [`node install.js` command specified in `package.json` as the install script (generated by `build-package.js`)](https://github.com/eugeneware/ffmpeg-static/blob/5.2.0/build-packages.js#L48) expects `node` to be in your path, which should always be the case with a functioning Node.js installation, even when using nvm.
