### ISSUE TITLE
split package to reduce install size

### ISSUE THREAD

**Issue by albertoVieiraNeto** [eugeneware/ffmpeg-static#20]
Hi.

im using ffmpeg-static together with fluent-ffmpeg (https://github.com/fluent-ffmpeg/node-fluent-ffmpeg) and that is causing a rather strange issue, the executables for **all** platforms are included and thus the total installed size is huge, over 200mb huge.

**Comment by derhuerst** [comment]
Jup, intended like this.

If you happen to know a smarter way to do this, let me know!

**Comment by derhuerst** [comment]
We could also create another package that downloads *one* binary as an `install` step, but that has multiple disadvantages. The tradeoff might be worth it some cases.

**Comment by derhuerst** [comment]
Okay, a plan:

1. Split this repo into 4 packages: `ffmpeg-static` and 3 platform-specific ones (e.g. `ffmpeg-static-linux`).
2. Let the CI build & publish all 4 packages.
3. Let `ffmpeg-static` declare the other 3 as [optional dependencies](https://docs.npmjs.com/files/package.json#optionaldependencies).
4. At runtime, let `ffmpeg-static` `require` the appropriate `ffmpeg-static-*` package.

**Comment by rajendrant** [comment]
The documentation around optional dependencies is not clear.
But it sounds like the optional packages will still be automatically [downloaded on install](https://coderwall.com/p/rmosmg/npm-package-json-optionaldependencies) ?

**Comment by derhuerst** [comment]
> But it sounds like the optional packages will still be automatically downloaded on install ?

True, but it's the only compromise I can think of that works without install scripts. You can run `npm i ffmpeg-static --no-optional`.

Let me know if you have any better ideas.

**Comment by jperl** [comment]
@derhuerst What is wrong with an install script? That is what [Puppeteer](https://github.com/puppeteer/puppeteer/blob/master/install.js) uses

**Comment by jperl** [comment]
@derhuerst What is wrong with an install script, which is what [Puppeteer uses](https://github.com/puppeteer/puppeteer/blob/master/install.js)?

Is it to prevent an issue in case that the mirrors die?  

In that case perhaps there could be separate packages per platform. And then this package could have an install script, which installs the appropriate package?

**Comment by derhuerst** [comment]
> What is wrong with an install script, is it to prevent an issue in case that the mirrors die?

It seems brittle:

- The server hosting the binaries might be down, and the URL is hardcoded.
- When a lot of people install ffmpeg-static (e.g. in CIs), there will be a lot of traffic on the server.
- You cannot easily audit the ffmpeg-static npm package properly, because it downloads an "arbitrary" executable on install.

> To avoid that, there could be separate packages per platform. Then this package could have an install script, which installs the appropriate package. What do you think of this approach?

That sounds like a reasonable trade-off. This is also [how the `node` npm packages do it](https://github.com/aredridel/node-bin-gen).

**Comment by jperl** [comment]
Ok I could work on a PR if you would be willing to accept it? This is what I was thinking:

- Change to a mono-repo with [lerna](https://github.com/lerna/lerna) so all packages can reside in one place
- Create one package per architecture ex. `@ffmpeg-static/linux-arm64`. I recommend using a scoped name for the subpackages since it would reserve future package names and seems to be what most mono-repos do ([babel](https://github.com/babel/babel), [jest](https://github.com/facebook/jest), [docusaurus](https://github.com/facebook/docusaurus)). But could name them `ffmpeg-static-linux-arm64` instead if you prefer.
- Have `ffmpeg-static` be the root package that contains the install script and exports the path

What are you recommendations for the proposed plan?

**Comment by derhuerst** [comment]
> Ok I could work on a PR if you would be willing to accept it?

Yes, I would!

> - Change to a mono-repo with [lerna](https://github.com/lerna/lerna) so all packages can reside in one place

I think lerna is overly complex and heavy for our use case:

- We have a manageable number of packages (7 right now), in contrast to Babel etc.
- The individual packages don't have dependencies.
- The individual packages don't have a lot of specific content (e.g. code, docs, tests). They will look almost the same.

Therefore I'm rather in favour of hard-coding the 7 packages for now. What do you think?

> Ok I could work on a PR if you would be willing to accept it? This is what I was thinking:

> - Create one package per architecture ex. `@ffmpeg-static/linux-arm64`. I recommend using a scoped name for the subpackages [...].
> - Have `ffmpeg-static` be the root package that contains the install script and exports the path

Sounds good!

**Comment by jperl** [comment]
Good point, there are no interdependencies so lerna is probably unnecessary at this point. Ok I am just working on wrapping up https://github.com/qawolf/qawolf/issues/282, then I will look into tackling this in the next few days or so.

**Comment by jperl** [comment]
@derhuerst I tested this approach by conditionally installing [`ffmpeg-static`](https://github.com/qawolf/qawolf/blob/master/packages/screen/src/install.js) and I no longer recommend it, because it breaks when you cache node_modules.

- It works initially to install the package
- In [CI](https://circleci.com/gh/qawolf/nytimes-example/20) when the cache is loaded, the top level package exists, and the install script will not run
- After `npm install` is run, the package installed with the install script is removed, since it is not part of package-lock.json

----

Instead of the previous approach, I now recommend hosting the platform specific binaries as assets of a [github release](https://help.github.com/en/github/managing-large-files/distributing-large-binaries)

- Create a prepublish script that uses [publish-release](https://github.com/remixz/publish-release) to upload the binaries
- Setup the install.js script to download the appropriate binary from the github release
- Do not have any sub-packages

What are your thoughts on this approach?

**Comment by derhuerst** [comment]
The dealbreaker aside that the sub-npm-package-based solution doesn't (seem to) work with lockfiles, I can see two "built-in" advantages that we lose by *not using* them:

- npm packages with baked-in binaries (e.g. `@ffmpeg-static/linux-64`) are robust. They will just work even if GitHub is down/censored/bankrupt.
- `npm` has proper built-in caching and offline support. Custom install scripts tend to miss these.

Let's use GitHub then.

> Instead of the previous approach, I now recommend hosting the platform specific binaries as assets of a github release and downloading those in install.js instead.

Not sure if our situation is worth adopting a tool geared towards packages with platform-native code, but [`prebuild`](https://github.com/prebuild/prebuild) and [`prebuild-install`](https://github.com/prebuild/prebuild-install) are commonly used for this.

But maybe writing a custom `instal.js`/`install.sh` is the better choice ([`prebuild-install` itself is quite heavy](http://npm.broofa.com/?q=prebuild-install)).

**Comment by jperl** [comment]
Yeah I really wanted it to work with npm packages but I could not find a way. I agree prebuild would be too heavy. It seems [npm recommends](https://github.com/npm/npm/issues/8585#issuecomment-186427170) the download [approach](https://github.com/Medium/phantomjs/blob/master/install.js) as well for binaries.

Re: GitHub releases want me to:

A. Setup [release-it](https://github.com/release-it/release-it/blob/master/docs/github-releases.md#attach-binary-assets) as an npm script to attach the binaries to the release.

or

B. Create a [GitHub action](https://github.com/actions/upload-release-asset#example-workflow---upload-a-release-asset) that downloads and attaches the binaries to a release every time a `vX` tag is pushed

**Comment by derhuerst** [comment]
Both is fine with me. I slightly prefer to let a GitHub action run on every Git tag (push).

**Comment by jperl** [comment]
Finally starting to work on this. Will do the GitHub action approach 👍

**Comment by mifi** [comment]
FWIW AFAIK electron is using the download approach

**Comment by jperl** [comment]
If anyone is waiting for #33 to be merged, you can use [@qawolf/ffmpeg-static](https://www.npmjs.com/package/@qawolf/ffmpeg-static) which has that merged in the meantime.
