### ISSUE TITLE
Install ffmpeg executable manually?

### ISSUE THREAD

**Issue by arj-ary** [eugeneware/ffmpeg-static#40]
Hey,
I have a question regarding the usage of this wrapper, currently installed this module using npm/yarn and i see ffmpeg exec in the node modules folder.

Should the executable be run manually? I was hoping this wrapper would also execute the binary, how do i run the exec file to install ffmpeg in the respective container? (Example: when deploying to PCF or any server)

**Comment by derhuerst** [comment]
> Should the executable be run manually?

Depends on what you mean. The job of the `ffmpeg-static` npm package is simply to provide a portable, cross-platform way for scripts to execute `ffmpeg`. Most of [`ffmpeg-static`'s dependents](https://github.com/eugeneware/ffmpeg-static/network/dependents) use it because they don't want to rely on the OS/system `ffmpeg` to be available or up-to-date.

> [...] how do i run the exec file to install ffmpeg in the respective container? (Example: when deploying to PCF or any server)

What is PCF?

When you're building an image, as you would usually do it with Kubenetes or FaaS runtimes like Google Cloud Run, `npm install` will invoke [`ffmpeg-static`'s `install.js` script](https://github.com/eugeneware/ffmpeg-static/blob/d0a5776e07a87bb11aa18fd39ba611585a346799/install.js), which will download the `ffmpeg` binary. During (container) runtime, you can then execute the binary.

**Comment by arj-ary** [comment]
@derhuerst thank for the clarification. I was needing to know if executing the binary on the container OS a separate task and reading your explanation, i understand we need to execute it as a separate task. I see this can be done by invoking the child process from node.js https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback in runtime and i plan to implement that way.
Can you think of any other approach from the top of your head that is maybe more efficient?

**Comment by derhuerst** [comment]
> i understand we need to execute it as a separate task.

Yes, it is up to you to actually *use* `ffmpeg`.

> I see this can be done by invoking the child process from node.js [...] in runtime and i plan to implement that way. Can you think of any other approach from the top of your head that is maybe more efficient?

Efficient in which way? Development time? Performance-wise, calling `ffmpeg` as a subprocess (with input & output being files) shouldn't be any slower than e.g. calling it from Bash.

There are many helpers related to this, e.g. [`execa`](https://github.com/sindresorhus/execa).

Also, there's a full-blown Node.js wrapper around ffmpeg: [`fluent-ffmpeg`](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg).

**Comment by arj-ary** [comment]
@derhuerst thank you for answering all the questions.

**Comment by derhuerst** [comment]
Please reopen if you have additional questions related to this topic.
