### ISSUE TITLE
Error: ffmpeg stream: write EPIPE 

### ISSUE THREAD

**Issue by Greigh** [eugeneware/ffmpeg-static#41]
Not sure if I'm writing everything correctly. It could be an issue with my code but I'm getting an error with EPIPE. 

`Error: ffmpeg stream: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}`

Let me know if I possibly messed up somewhere because it is very possible. I'm using v4.1.0 of ffmpeg-static on macOS [not sure if that matters].

**Comment by derhuerst** [comment]
Did this error occur during installation or in your code? Please provide more information about your setup, e.g. your `npm install` logs and your code.

**Comment by Greigh** [comment]
It did not happen during installation. It is in my code. I am getting it with a skip command that I'm trying to implement. I've been trying to log errors within my code, and I can't figure out where it is coming from. A play function works fine. I have even tried it with different links.

**Comment by derhuerst** [comment]
I can't help you without more context, i.e. your code and/or error logs.

The error you quoted above should have a stack trace printed below. Can you paste that here?

---

Also, you can manually verify that the `ffmpeg-static` installation worked (regardless of the bug in your code):

1. Jump to the directory/project where you installed `ffmpeg-static`.
2. Run a Node REPL: `node`.
3. Copy the path that `require('ffmpeg-static')` prints (it's `/Users/j/web/ffmpeg-static/ffmpeg` on my machine).
4. Exit the Node REPL by typing `.exit` or pressing Ctrl+D.
5. Paste the path and append ` --help`. The ffmpeg help should be printed.

**Comment by Greigh** [comment]
Here's the code I am using it with. I am only getting the error in the !skip command. 

https://ghostbin.co/paste/z5vutgyk 
Password: ffmpeg

The `--help` append works fine. As I've stated above the !skip is the only command that doesn't work with the code above. It could be an error with my code, but I'm not sure why I would be getting the ffmpeg error then.

**Comment by derhuerst** [comment]
At a glance, it looks like your problem is not related to `ffmpeg-static` at all, because you're not using `ffmpeg-static` in this file. You're using `ffmpeg-binaries`, which is a different project.

Sorry, but I don't have the time & motivation to help you debug a problem that's likely unrelated. Please reopen this Issue if you have a short code snippet that reproduces a problem with `ffmpeg-static`.

**Comment by Alexmdz77** [comment]
Hi, I have the same problem with ffmpeg static, I tried to reinstall everything but nothing changes.

**Comment by derhuerst** [comment]
@Alexmdz77 please share a stripped-down code snippet that triggers the error.

**Comment by Alexmdz77** [comment]
Here is an snippet of the code that generates the error:
```js
const stream = ytdl(song.url, {
            filter: 'audioonly',
            quality: 'highestaudio',
            dlChunkSize: 0,
            highWaterMark: 1 << 25,
        }).on('error', err => {
            return console.log(err)
        });
        setTimeout(() => {
            if (queue.dispatcher) queue.dispatcher.destroy();
            let dispatcher = queue.connection.play(stream, {
                seek: seek / 1000 || 0,
            });
            queue.dispatcher = dispatcher;
            // Set volume
            dispatcher.setVolumeLogarithmic(queue.volume / 200);
            // When the song ends

            dispatcher.on('error', (error) => {
                return console.log(error);
            });
            dispatcher.on('finish', () => {
                // Play the next song
                return this._playSong(guildID, false);
            });
        }, 1000);
```
I would also like to specify that the bot is hosted on a VPS but that locally it works perfectly, the VPS provider tells me that there are no restrictions on their side.

**Comment by derhuerst** [comment]
That script doesn't seem to use `ffmpeg-static`.

**Comment by Alexmdz77** [comment]
Why does the error mention ffmpeg?
sorry but i don't know where i should be asking for this

**Comment by derhuerst** [comment]
> Why does the error mention ffmpeg?

One of the libraries in your script might use ffmpeg underneath, yes. But it *might* also use a different `ffmpeg` binary than the one provided by `ffmpeg-static`.

I won't do all the guesswork involved to figure out if one of the libraries you're using uses `ffmpeg-static`, sorry. I'll happily fix bugs in `ffmpeg-static` or improve its docs; With problems that are technically not related to `ffmpeg-static`, most of the time, I'll indicate where else to look for the error. But I won't ping-pong-ask for all the relevant details.

No matter where (at wich project/forum) you ask, it always helps others (particularly the maintainer(s)) to reduce your script to minimal variant that still produces the error, and to make it easy for others to run it. That could mean in your case:

- Checking if the error is caused by `ytdl()`, or by whatever is behind `queue`. Remove the parts that *don't* cause the error.
- Making the script runnable as-is. Your current script has no definitions for `song`, `queue`, `dispatcher`, etc.
- Providing the versions of your dependencies. That could mean pasting the `package.json` or the output of `npm ls --depth 10`.
- Providing more context info: OS, Node.js version, npm version, etc.
