### ISSUE TITLE
Adding git versions

### ISSUE THREAD

**Issue by FallingSnow** [eugeneware/ffmpeg-static#5]
https://github.com/FallingSnow/ffmpeg-static/commit/917aaf3715a5eb7c285071c8b65989ff292d6645

What do ya think? For now only linux works, have to write the unzipping part for windows.

It seems that adding download support for linux ffmpeg stable will also be possible using this method.

**Comment by chovy** [comment]
submit a PR. is there no windows safe zip lib? i find that hard to believe.

**Comment by eugeneware** [comment]
I think it's a great feature to have. However, part of bundling ffmpeg binaries with the npm module was to reduce external dependencies, and indeterminate builds and installs due to networks failures, delays, etc. It's one of the design goals for this module.

It's probably best to do this in a fork and publish as a separate module for now.

**Comment by derhuerst** [comment]
closing.
