### ISSUE TITLE
error installing ffmpeg-static with npm command

### ISSUE THREAD

**Issue by DariusKing** [eugeneware/ffmpeg-static#52]
Hi, i'm new using this node package, when i try to install it on my discord bot proyect i can't do it, cause every time i receive this error:

PS D:\Escritorio\main-bot> npm install ffmpeg-static
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/derhuerst/http-basic.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
this is my log file of that error
https://paste.ofcode.org/zx3pxqKd8XcDbDr5eYvUqy

![Screenshot_28](https://user-images.githubusercontent.com/34556842/87865315-87a78900-c928-11ea-8e69-1cab50c5be8c.jpg)

**Comment by derhuerst** [comment]
Because #50, I let `ffmpeg-static` use a [Git](https://git-scm.com)-hosted dependency. This means that, currently, you need to have the `git` executable in your [`$PATH`](https://en.wikipedia.org/wiki/PATH_%28variable%29) to install `ffmpeg-static`.

Since the issue described in #50 is resolved, I changed the dependency back to be npm-hosted, and I will publish this change now.

**Comment by derhuerst** [comment]
Published as `ffmpeg-static@4.2.6`.

Please reopen if the problem persists for you.
