### ISSUE TITLE
 output video is black on linux 

### ISSUE THREAD

**Issue by forleetcode** [eugeneware/ffmpeg-static#56]
hey i trying to record my screen using ffmpeg static but the output video is black . this my code and i am using linux ubuntu 20
i dont know this is because of linux i dont know help
this is my code

```js
const ffmpeg = require("ffmpeg-static");
const { spawn } = require("child_process");
console.log(ffmpeg)
const process = spawn(
    ffmpeg,
  ["-probesize", "10M", "-f", "fbdev", "-r", "60", "-i", "/dev/fb0", "-f", "avi", "-"],
  { stdio: "pipe" }
);
const stream = process.stdout;


const { createWriteStream } = require("fs");

const file = createWriteStream("capture.avi");
stream.pipe(file);
```

**Comment by derhuerst** [comment]
Just like with #55, I assume that this is actually due to the [binary that `ffmpeg-static` downloads](https://github.com/eugeneware/ffmpeg-static/tree/18acfdfc0b852863d46a8cbe3873a2c9e3fc792e#sources-of-the-binaries) or due to your setup (window server, graphics card, ffmpeg config, etc). Please check if it works via command line:

```bash
$(node -p 'require('ffmpeg-static')') -probesize 10M -f fbdev -r 60 -i /dev/fb0 -f avi - >capture.avi
```

**Comment by derhuerst** [comment]
I'm going to close this Issue, because it seems that I cannot fix it here in `ffmpeg-static`.
