### ISSUE TITLE
this library license problem?

### ISSUE THREAD

**Issue by tak40548798** [eugeneware/ffmpeg-static#59]
Can I use this library for commercial software?

What is the difference between this library and "node-fluent-ffmpeg"?

I now use "node-fluent-ffmpeg" and call ffmpeg binary file to do h.264 file conversion

But the ffmpeg binary file contains libx264

libx264 is a GPL license

If I use libx264 in ffmpeg

Do I also have to follow the GPL?

The question I want to ask is whether there is libx264 in the binary file of the library?

**Comment by derhuerst** [comment]
#8 has a discussion on why the `ffmpeg-static` package has been relicensed to `GPL-3.0`. Also, the npm package (usually in `node_modules/ffmpeg-static`) contains the license of the respective `ffmpeg`.

**Comment by derhuerst** [comment]
I am not a lawyer, so don‘t rely on my statements.

> Can I use this library for commercial software?

AFAIK, if you make derived work available as GPL, yes.

> What is the difference between this library and "node-fluent-ffmpeg"?

`fluent-ffmpeg` abstracts the `ffmpeg` CLI into a JavaScript-friendly API. `ffmpeg-static` just contains/downloads an `ffmpeg` binary. You can combine both if you want.

> But the ffmpeg binary file contains libx264
> 
> libx264 is a GPL license
> 
> If I use libx264 in ffmpeg
> 
> Do I also have to follow the GPL?

AFAIK yes, because the whole binary contained in `ffmpeg-static` is distributed under GPL.
