### ISSUE TITLE
Compress releases?

### ISSUE THREAD

**Issue by coolaj86** [eugeneware/ffmpeg-static#69]
Would you be willing to compress the releases?

Using `xz` (LZMA2), which is usually on all Linux systems by default, the download size can be reduced by nearly 80%.

Using `gzip` (Deflate), which is included natively on Mac, Linux, and even **Windows 10**, the size can be reduced by 70%.

`zip` (Deflate) is supported by Windows 10 `tar.exe`. It's also supported by PowerShell... but the PowerShell implementation is very slow.

```txt
.rwxr-xr-x aj staff   71 MB Sun Aug 16 13:03:49 2020 ffmpeg-4.3.1-darwin-x64
.rwxr-xr-x aj staff 21.4 MB Sun Aug 16 13:03:49 2020 ffmpeg-4.3.1-darwin-x64.bz2
.rwxr-xr-x aj staff 22.7 MB Sun Aug 16 13:03:49 2020 ffmpeg-4.3.1-darwin-x64.gz
.rwxr-xr-x aj staff 15.7 MB Sun Aug 16 13:03:49 2020 ffmpeg-4.3.1-darwin-x64.xz
.rw-r--r-- aj staff 22.7 MB Wed Nov 18 17:21:51 2020 ffmpeg-4.3.1-darwin-x64.zip
```

One of the reasons that I like the idea of ffmpeg-static is that it saves having to download 400mb of `brew`. However, the size could be *much* smaller still.

**Comment by derhuerst** [comment]
> Would you be willing to compress the releases?

Although I actually consider this something to be done by GitHub/AWS; It would automagically make people wait less & waste less data/CO2, since most HTTP clients request with `Accept-Encoding: gzip, deflate` nowadays. I'm willing to implement this "manually" for the sake of bandwidth savings, though.

[Since Node.js v10 has support for gzip, deflate & Brotli](https://nodejs.org/docs/latest-v10.x/api/zlib.html), we can pick any of those three, with a rather aggressive compression level. Do you recommend a specific one?

**Comment by derhuerst** [comment]
I'll try with gzip.

**Comment by coolaj86** [comment]
Those numbers are all with the default.

I’d go with the maximum compression since gzip uses little memory and the CPU usage is a one-off on the side of the compressor.

I hadn’t thought that S3 would compress binary files.
