### ISSUE TITLE
events.js:291 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by muhimur9049** [eugeneware/ffmpeg-static#72]
Hello, I am using ffmpeg-static package for a NodeJS Project (Discord bot) and I randomly sometimes get this error. Any idea what's wrong or how I can stop/prevent this?

![image](https://user-images.githubusercontent.com/52611945/103432419-77205d80-4bac-11eb-8997-3f0b907e6fab.png)

**Comment by chovy** [comment]
EAGAIN usually means something is missing. try `rm -rf node_modules`

**Comment by muhimur9049** [comment]
After that what do I do?

**Comment by chovy** [comment]
`npm i` and try again if that didn't work i think there's a build error or something.

**Comment by muhimur9049** [comment]
Just removed every single package module from package.json and also removed node_modules and reinstalled them all and there hasn't been any package vulnerabilities yet. Hopefully it fixes it. If it still doesn't fix it, what else should I do?

**Comment by chovy** [comment]
try recompiling ffmpeg

**Comment by muhimur9049** [comment]
And that would be done with npm rebuild <package>?

**Comment by derhuerst** [comment]
@muhimur9049 This is very likely due to how you're interacting with the spawned `ffmpeg` process, but let's make sure it's not `ffmpeg-static`'s fault:

1. Make sure you're running a supported version of Node.js. `ffmpeg-static` requires at least `10.x`.
2. Install your dependencies, including `ffmpeg-static`, and check that the install logs don't show errors. During the install process, `ffmpeg-static` attempts to download `ffmpeg` from a GitHub Release; If this fails for some reason, the respective error will show up in the install logs. In addition, verify that the downloaded `ffmpeg` binary works by running `$(node -p 'require("ffmpeg-static")') --help`.

**Comment by muhimur9049** [comment]
Node version is 12, and the ffmpeg-static version is 4.2.7 when doing npm ls ffmpeg-static and I also followed those instructions, but it still seems to be doing this randomly (rare though). My bot is shards though and is in a couple thousand servers, could that be why and if so how can I prevent and fix it?

**Comment by derhuerst** [comment]
As I said, you can confirm that the `ffmpeg` has been downloaded correctly by running `$(node -p 'require("ffmpeg-static")') --help`.

> I also followed those instructions, but it still seems to be doing this randomly (rare though).

That sounds a lot like there's a race condition involved.

> My bot has shards though and is in a couple thousand servers, could that be why and if so how can I prevent and fix it?

That is not related to `ffmpeg-static`. Try to reduce the number of potential factors that might cause your problem, e.g. use the same OS, same Node.js version, lock dependency versions, run only one instances/process per machine, etc.

> And could it also mean Ffmpeg just crashed?

Maybe. Double-check all your error handling logic.

I will close this Issue, as it seems unrelated to `ffmpeg-static`.
