### ISSUE TITLE
Question about ffmpeg over http proxy

### ISSUE THREAD

**Issue by Murena7** [eugeneware/ffmpeg-static#73]
Hello, I try download video stream over http proxy and pass proxy address over -http_proxy argument (i read this in ffmpeg documentation) but this not get any effect. What i do wrong ? Please explain how i can download some stream video over  proxy server ?
Thanks

**Comment by derhuerst** [comment]
This package just provides `ffmpeg` binaries; It does not modify them, just automatically downloads a binary for other npm package to use.

This is why any `ffmpeg` command that works with a binary that has been manually downloaded from the website *should* also work with the `ffmpeg-static`-provided binary.

Please make sure that your command is correct, and that the ffmpeg version mentioned by the documentation matches your local version. You can get help with using ffmpeg via one of the [official support channels](https://ffmpeg.org/contact.html).

If you think that your problem is indeed caused by (or related to) `ffmpeg-static`, please reopen this Issue!
