### ISSUE TITLE
Clarify possible relationship of binary builds to GPL

### ISSUE THREAD

**Issue by maxwellb** [eugeneware/ffmpeg-static#8]
I am concerned that ffmpeg-static is presented by you as "BSD-3-clause" license, but you distribute ffmpeg, which is GPL/LGPL licensed. There is no source code or accompanying license for your ffmpeg static builds, so it is unclear what license they are under. This could present challenges for anyone consuming ffmpeg-static from NPM who might assume the package is under BSD-3-clause as listed.

These are my personal concerns and opinions. I am not a lawyer, and received no legal advice for this issue, nor should this issue be construed as legal advice. Thank you for your consideration.

**Comment by fzdz1010** [comment]
They have an example in the AppImageKit wiki showing that libx264 is enabled at least for the Linux build:
https://github.com/AppImage/AppImageKit/wiki/Bundling-FFmpeg

Based on the documentation on the ffmpeg site, I think that would make at least the Linux version GPL licensed.

**Comment by derhuerst** [comment]
What steps forward do you propose? Some that I can think of:

- Include the ffmpeg license in the npm package.
- Include a link to the source code in the npm package.
- Inform about the `ffmpeg` licensing in the readme.

**Comment by maxwellb** [comment]
One option, my personal suggestion:
[ ] Update package.json license to gpl-3.0
[ ] Extract a bin-readme.txt to files collection. For zeranoe.com and johnvansickle.com, extract readme.txt from the archive. For evermeet.cx builds you could parse like this
    `curl -s https://evermeet.cx/pub/ffmpeg/ | gawk '/<code>/ { on = "true"; } /<.code>/ { on="false";stop="true" } (on=="true" && stop!="true") {print}" | tail -n "+2" | python -c 'import html, sys; print(html.unescape(sys.stdin.read().replace("<br>","")))'`

Yes, you could also add links to the source. It's probably fine just to link to the main page of zeranoe, johnvansickle, and evermeet builds, and have the reader use the tag information in the build-readme.txt to navigate to the third-party site.

**Comment by derhuerst** [comment]
Why license to GPLv3 and not LGPLv2? From the ffmpeg `LICENSE.md`:

> Most files in FFmpeg are under the GNU Lesser General Public License version 2.1 or later (LGPL v2.1+). Read the file `COPYING.LGPLv2.1` for details. Some other files have MIT/X11/BSD-style licenses. In combination the LGPL v2.1+ applies to FFmpeg.
>
> Some optional parts of FFmpeg are licensed under the GNU General Public License version 2 or later (GPL v2+). See the file `COPYING.GPLv2` for details. None of these parts are used by default, you have to explicitly pass `--enable-gpl` to configure to activate them. In this case, FFmpeg's license changes to GPL v2+.

**Comment by maxwellb** [comment]
I am not a lawyer, but the builds being used by the package have had `--enable-gpl` applied it would seem

**Comment by mifi** [comment]
It seems that this is not that simple to determine. Whether the software that uses ffmpeg needs to follow ffmpeg's license (LGPL/GPL) depends on how close the relationship between the two are. How closely they communicate seems to be kind of a grey area in the GPL at least.
See:
- https://www.gnu.org/licenses/gpl-faq.html#NFUseGPLPlugins
- https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins

So I think there is no right answer for whether the license of this lib should be GPL or anything else. You might want to say that it should indeed be GPL, because then someone who is scanning their node_modules dependencies for licenses or looking at the license before considering using this package, will see that there might potentially be a legal issue, rather than just thinking there is no issue.

**Comment by maxwellb** [comment]
I acknowledge the predicament. Indeed, I first discovered the issue when doing a license scan of a project's dependencies. And also running ffmpeg version/info output.

Perhaps the project does not need to take a stance, but rather can ship two binaries in each package, and allow the consumer to make use of whichever version they evaluate to be correct for their situation.

**Comment by mifi** [comment]
Problem with shipping with two binaries is even bigger size. Perhaps better would be to have multiple published variants of the package. Maybe ffmpeg-static-lgpl and ffmpeg-static-gpl. Then the license field in package json can be set to lgpl or gpl correspondingly.

**Comment by maxwellb** [comment]
If that's a possibility, it would be a win for my original use case. It does appear that of the three current sources for binaries (Windows, Mac, Linux), all third parties currently build with --enable-gpl.
I'm not sure what needs to happen to produce upstream lgpl binaries, but I could start investigating an Azure pipeline if that would help.
In addition to separate package names, even a prerelease version or tag might be appropriate.
It looks like ffmpeg-static will be changing to an install script approach with #20 so any approach for this issue probably needs to follow behind it.

**Comment by jperl** [comment]
I will change #33 to support a FFMPEG_URL parameter. So you could support downloading any version.

**Comment by derhuerst** [comment]
> Yes, you could also add links to the source. It's probably fine just to link to the main page of zeranoe, johnvansickle, and evermeet builds [...].

[We do that by now.](https://github.com/eugeneware/ffmpeg-static/blob/f428a773145558ade2b09213922ebfe3798fa27e/README.md#sources-of-the-binaries)

> Problem with shipping with two binaries is even bigger size.

As of #33, this won't be a problem anymore.

> I'm not sure what needs to happen to produce upstream lgpl binaries, but I could start investigating an Azure pipeline if that would help.

I'd like not to start building `ffmpeg` binaries as part of this project. It's a slippery slope that will replicate a lot of build infrastructure that other people (like the binary providers mentioned in the readme) have already set up. I would like to keep this package just as another, better-versioned "distribution channel" of the binaries.

**Comment by maxwellb** [comment]
OK, I think this issue is likely to be closed from what I am reading. Allow me to capture the original spirit of the issue one more time: as a distribution channel for the binaries referenced in the README, this package is listed in registries and scanned in the enteprise as BSD-3-Clause, but the binaries are built GPL. At the least, this is a source of confusion.
The sources referenced in the README currently only point to the home page of the referenced builds. Could an interim update of this issue be to capture information about which upstream build was incorporated, so that a consumer could access the exact source version?
Thank you for the comments thusfar, and I support closing the issue since it's been thoroughly reviewed.

**Comment by jperl** [comment]
One potential alternative solution would be to make the download url configurable with an environment variable. That way @maxwellb could do the azure pipeline in another project and still use the download mechanism of this one. I would be happy to submit a PR for that.

**Comment by derhuerst** [comment]
> [...] as a distribution channel for the binaries referenced in the README, this package is listed in registries and scanned in the enteprise as BSD-3-Clause, but the binaries are built GPL. At the least, this is a source of confusion.

I definitely agree, this is confusing. IANAL, but keep in mind that the GPL is very unintuitive *anyways* regarding non-compilation usage (e.g. with scripting languages & via `spawn`). Scanning library metadata is technically not enough to prevent license violations.

Having said that, I'm fine with relicensing this project to GPL.

> The sources referenced in the README currently only point to the home page of the referenced builds. Could an interim update of this issue be to capture information about which upstream build was incorporated, so that a consumer could access the exact source version?

Yes, I'd appreciate that a lot; Also, a notice regarding the GPL-built binaries would be helpful. PR welcome!

> One potential alternative solution would be to make the download url configurable with an environment variable.

That would work, but would be additional complexity for (AFAIK, IANAL) a non-problem.

**Comment by bobpaul** [comment]
So it looks like the fix for this is that `node_modules/ffmpeg-static/package.json` declares a `GPLv3` or later license. This is good, as it causes it to show that when I run `yarn licenses list`. Still a little confusing since the `LICENSE` file that's in there (for this project) is a BSD style license. I think a `LICENSE.ffmpeg` file should be created, which can just be the LICENSE file from the archive.

Also looking over https://www.ffmpeg.org/legal.html they recommend that including the `./configure` commandline so users know how this particular ffmpeg was built. Is this information stored anywhere and I'm just not looking in the first spot? A log of the exact download URL used would be nice, too.

Looking at the archive sources, the build info is included in the `README` for both the [Windows](https://ffmpeg.zeranoe.com/builds/win64/static/) and [OSX](https://ffmpeg.zeranoe.com/builds/macos64/static/) on the zeranoe.com, the top of the page for the Mac builds on evermeet.cx, and is described sufficiently to determine the correct `./configure` commandline in the `readme.txt` for the linux builds on johnvansickle.com.

**Comment by derhuerst** [comment]
> I think a `LICENSE.ffmpeg` file should be created, which can just be the LICENSE file from the archive.

This will happen with the next ffmpeg version: [The `install` script will download the ffmpeg license accompanying the binary to `ffmpeg.LICENSE`.

> Also looking over https://www.ffmpeg.org/legal.html they recommend that including the `./configure` commandline so users know how this particular ffmpeg was built. Is this information stored anywhere and I'm just not looking in the first spot? A log of the exact download URL used would be nice, too.

[The readme has links to the binary providers.](https://github.com/eugeneware/ffmpeg-static/blob/525755d9d23deddaa392aa98fcbd27269f96df94/README.md#sources-of-the-binaries) Do you think we should do more than link to them?

**Comment by bobpaul** [comment]
I mean we can always do more =D

So I think technically anyone distributing a GPL binary has to provide the source, but generally copyright holders seem to accept a link to an upstream host of the source code, that's as much as the people who are building the binaries you redistribute are doing.

But the upstream binary providers are also providing information on which specific version (ie, git revision or git tag name) and information on how the binary is built. This project is stripping some of that information out (here's your binary, it came from there but you'll have to do some digging to know specifics).

Why this is important to me is that I'm looking at using this as part of an electron app rather than a server side nodejs project. With a server side nodejs app, the app is just running (not distributing)  FFmpeg, so end-users don't even have to know. And this project can reasonably say that it's not distributing the `ffmpeg` binary but rather facilitating the distribution from well known providers. But in an electron app I _would_ be directly distributing and my users will reasonably be able to demand that I provide the specific source code used, configure options, etc so that they can build their own copy of FFmpeg to replace the one that came with my installer, dmg, etc.

----

Just commenting on the providers:

I really like how the Zeranoe has a README with the `./configure` options and a link to the exact git commit for each build. Ideally, I'd provide that level of info in a README file included in my electron app. Since the configure options are likely to change over time and also impact which license terms can apply to the binary (GPL vs LGPL, v2+ vs v3, etc)  knowing these options really is a bit more important for FFmpeg than it is for other projects. 

Jon Sickle's builds don't provide the exact configure options in his readme, but do include the libraries used and there's a 1:1 mapping from library to configure option, so close enough. For both Zeranoe and Jon Sickle's builds, simply passing through the upstream README file would enable me to easily include that info when packaging my app.

Evermeet provides less info in the actual download (the filename contains the either git hash or git tag name, depending on the build) and the configure options are just at the top of the download page and so they might be have changed in a month or a year when a user tries to look up that info. If I just tell "OSX users that the FFmpeg I gave them was version X from Evermeet, here's a link to the official FFmpeg git repository" they might struggle to figure out the exact version and build options. BUT... Evermeet does have an API that returns specific build info for each binary. So if a user (or this project, or my packaging scripts when building an electron app) knows the original file name, that API can provide all the build info.

**Comment by derhuerst** [comment]
> Just commenting on the providers: [...]

Let's pull this info into the `ffmpeg-static` release, as long as this is done in an automated (and reasonable robust) way! Contributions welcome, please create a follow-up Issue, or even a PR right away.

**Comment by lingo** [comment]
For anyone wanting further clarification the latest linux binary in this package, at time of writing, has these flags, i.e. definitely the GPL (not LGPL) version.

```
ffmpeg version 7.0.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
...
```
