### ISSUE TITLE
Missing Option

### ISSUE THREAD

**Issue by pl4yradam** [eugeneware/ffmpeg-static#81]
Hi Guys, 

Im trying to use the segmented option: **segment_list_entry_prefix**

Error returned:
`@@  Option segment_list_entry_prefix not found.`

Is this a difference between 4.3 and 4.4?

Array Code:
```
// Segmentation
        "-f", "segment",
        "-segment_time", "4",
        "-segment_wrap", "5",
        "-segment_list", listName,
        "-segment_list_size", "5", location,
        "-segment_list_entry_prefix", "a-prefix",
        ```

**Comment by derhuerst** [comment]
`ffmpeg-static@latest` currently installs an ffmpeg 4.3 binary (until #78 is done).

You can check the flags supported by this version by running `node_modules/ffmpeg-static/ffmpeg --help` and by reading the ffmpeg 4.3 docunentation.

I can't help you with ffmpeg-specific questions, sorry; Maybe someone else can.

Therefore, I'm going to close this Issue. Please don't hesitate to re-open if the problem turns out to be related to `ffmpeg-static`!
