### ISSUE TITLE
how to extract audio from video?

### ISSUE THREAD

**Issue by makarhuyaker** [eugeneware/ffmpeg-static#95]

**Comment by derhuerst** [comment]
There are plenty of answers just a search away, e.g. [this StackOverflow answer](https://stackoverflow.com/a/27413824/1072129). If you want to use the `ffmpeg` binary from `ffmpeg-static` to run the code mentioned, use `$(node -p 'require("ffmpeg-static")')` instead of just `ffmpeg`:

```bash
$(node -p 'require("ffmpeg-static")') -i input-video.avi -vn -acodec copy output-audio.aac
```

Also, please note that this repo merely *downloads* ffmpeg binaries, so we can't provide support for general questions about how to use ffmpeg here. (Except if it is an issue specific to the way `ffmpeg-static` works.)
